// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcirqwrvrlufvsuyznhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjaXJxd3J2cmx1ZnZzdXl6bmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY1NTk1MjIsImV4cCI6MjA1MjEzNTUyMn0.Qz6PNHed5_EUKxeaH0g77MX0WsGcYm5D_3b0KnqyiQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);